//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklep_Internetowy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adres
    {
        public int Id_adresu { get; set; }
        public string miasto { get; set; }
        public string powiat { get; set; }
        public string ulica { get; set; }
        public Nullable<int> numer_domu { get; set; }
        public Nullable<int> numer_lokalu { get; set; }
        public Nullable<int> Klient_Id_klienta { get; set; }
    }
}
