//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklep_Internetowy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dane_kontaktowe
    {
        public int Id_kontaktu { get; set; }
        public Nullable<int> numer { get; set; }
        public string emial { get; set; }
    
        public virtual Pracownik Pracownik { get; set; }
        public virtual Klient Klient { get; set; }
    }
}
