//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklep_Internetowy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faktura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Faktura()
        {
            this.Faktura_produktuSet = new HashSet<Faktura_produktu>();
        }
    
        public int numer_faktury { get; set; }
        public int Id_klienta { get; set; }
        public Nullable<System.DateTime> data_sprzedaży { get; set; }
        public Nullable<double> wartość_netto { get; set; }
        public Nullable<bool> czy_dostawa { get; set; }
        public Nullable<double> procent_podatku { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faktura_produktu> Faktura_produktuSet { get; set; }
    }
}
