//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklep_Internetowy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategoria_produktu
    {
        public int Id_kategoria_produktu { get; set; }
        public Nullable<int> Id_producenta { get; set; }
        public Nullable<int> Id_kategorii { get; set; }
    
        public virtual Produkt Produkt { get; set; }
        public virtual Producent Producent { get; set; }
        public virtual Kategoria Kategoria { get; set; }
    }
}
