//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklep_Internetowy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klient
    {
        public int Id_klienta { get; set; }
        public Nullable<int> Id_kontaktu { get; set; }
        public Nullable<int> Id_adresu { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
    }
}
