//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklep_Internetowy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adres> AdresSet { get; set; }
        public virtual DbSet<Klient> KlientSet { get; set; }
        public virtual DbSet<Pracownik> PracownikSet { get; set; }
        public virtual DbSet<Dane_kontaktowe> Dane_kontaktoweSet { get; set; }
        public virtual DbSet<Produkt> ProduktSet { get; set; }
        public virtual DbSet<Faktura> FakturaSet { get; set; }
        public virtual DbSet<Faktura_produktu> Faktura_produktuSet { get; set; }
        public virtual DbSet<Zdjęcia> ZdjęciaSet { get; set; }
        public virtual DbSet<Kategoria_produktu> Kategoria_produktuSet { get; set; }
        public virtual DbSet<Kategoria> KategoriaSet { get; set; }
        public virtual DbSet<Producent> ProducentSet { get; set; }
    }
}
