//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklep_Internetowy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pracownik
    {
        public int Id_pracownika { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public System.DateTime data_zatrunienia { get; set; }
        public int Id_adresu { get; set; }
        public int Id_kontaktu { private get; set; }
    }
}
