//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklep_Internetowy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produkt()
        {
            this.Kategoria_produktu = new HashSet<Kategoria_produktu>();
            this.Zdjęcia = new HashSet<Zdjęcia>();
        }
    
        public int Id_produktu { get; set; }
        public Nullable<int> Id_kategorii_produktu { get; set; }
        public string nazwa { get; set; }
        public string opis { get; set; }
        public Nullable<int> Id_zdjecia { get; set; }
        public Nullable<double> cena_brutto { get; set; }
        public Nullable<double> cena_netto { get; set; }
        public Nullable<double> procent_vat { get; set; }
        public int Faktura_produktuId_faktura_produktu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kategoria_produktu> Kategoria_produktu { get; set; }
        public virtual Faktura_produktu Faktura_produktu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zdjęcia> Zdjęcia { get; set; }
    }
}
