//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklep_Internetowy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produkt()
        {
            this.Faktura_produktuSet = new HashSet<Faktura_produktu>();
            this.ZdjęciaSet = new HashSet<Zdjęcia>();
        }
    
        public int Id_produktu { get; set; }
        public int Id_kategorii_produktu { get; set; }
        public string nazwa { get; set; }
        public string opis { get; set; }
        public Nullable<int> Id_zdjecia { get; set; }
        public Nullable<double> cena_netto { get; set; }
        public Nullable<double> procent_vat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faktura_produktu> Faktura_produktuSet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zdjęcia> ZdjęciaSet { get; set; }
        public virtual Kategoria_produktu Kategoria_produktu { get; set; }
    }
}
