//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sklep_Internetowy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zdjęcia
    {
        public int Id_zdjecia { get; set; }
        public string nazwa { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<int> Id_produktu { get; set; }
        public Nullable<int> ProduktId_produktu { get; set; }
    
        public virtual Produkt ProduktSet { get; set; }
    }
}
